shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

# Must be sourced after other plugins and widgets.
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
