add_newline = true
format = "$hostname$directory$git_branch$git_status$python$cmd_duration$line_break$character"

[character]
success_symbol = "[❯](blue)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[hostname]
ssh_only = true
ssh_symbol = ""
format = "[$hostname]($style) "
style = "yellow"

[directory]
style = "blue bold"
truncation_length = 3
truncate_to_repo = true
read_only = " ro"

[git_branch]
symbol = ""
style = "purple"
format = "[$branch]($style) "

[git_status]
style = "red"
format = "([$all_status$ahead_behind]($style) )"
conflicted = "=${count}"
ahead = ">${count}"
behind = "<${count}"
diverged = ">${ahead_count}<${behind_count}"
untracked = "?${count}"
stashed = "*${count}"
modified = "!${count}"
staged = "+${count}"
renamed = "r${count}"
deleted = "-${count}"

[python]
symbol = ""
style = "yellow"
format = '[($virtualenv )]($style)'
# Display only an activated environment, without probing project files.
detect_extensions = []
detect_files = []
detect_folders = []

[cmd_duration]
min_time = 2000
format = "[$duration]($style) "
style = "yellow"
