palette = 0=#FAF3E1
palette = 1=#F85550
palette = 2=#8DA200
palette = 3=#DEA000
palette = 4=#36A87E
palette = 5=#DF69BA
palette = 6=#3A94C4
palette = 7=#4F5B62
palette = 8=#4F5B62
palette = 9=#297CA6
palette = 10=#258C67
palette = 11=#758700
palette = 12=#E6271C
palette = 13=#CA43A3
palette = 14=#DBC988
palette = 15=#6E7F88

# Other settings
background = #FAF3E1
foreground = #4F5B62
cursor-color = #4F5B62
cursor-text = #4F5B62
selection-background = #D3DFE6
selection-foreground = #4F5B62
