palette = 0=#2C343A
palette = 1=#E67C7F
palette = 2=#A9C181
palette = 3=#DDBD7F
palette = 4=#7FBCB4
palette = 5=#D69AB7
palette = 6=#83C193
palette = 7=#E7DCC4
palette = 8=#45525C
palette = 9=#ED9294
palette = 10=#B0CE7B
palette = 11=#EDC77A
palette = 12=#7AC9C0
palette = 13=#E5A7C4
palette = 14=#7DD093
palette = 15=#B2A790

# Other settings
background = #2C343A
foreground = #E7DCC4
cursor-color = #EBE2CF
cursor-text = #E7DCC4
selection-background = #615B51
selection-foreground = #E7DCC4
