palette = 0=#1F1F28
palette = 1=#E46A78
palette = 2=#98BC6D
palette = 3=#E5C283
palette = 4=#7EB3C9
palette = 5=#957FB8
palette = 6=#7EB3C9
palette = 7=#DDD8BB
palette = 8=#DDD8BB
palette = 9=#7BC2DF
palette = 10=#7BC2DF
palette = 11=#9EC967
palette = 12=#EC818C
palette = 13=#A98FD2
palette = 14=#3C3C51
palette = 15=#A8A48D

# Other settings
background = #1F1F28
foreground = #DDD8BB
cursor-color = #E6E0C2
cursor-text = #DDD8BB
selection-background = #49473E
selection-foreground = #DDD8BB
