palette = 0=#E5EDE6
palette = 1=#A8334C
palette = 2=#567A30
palette = 3=#944927
palette = 4=#286486
palette = 5=#88507D
palette = 6=#3B8992
palette = 7=#202E18
palette = 8=#202E18
palette = 9=#1D5573
palette = 10=#2B747C
palette = 11=#3F5A22
palette = 12=#94253E
palette = 13=#7B3B70
palette = 14=#B3C6B6
palette = 15=#415934

# Other settings
background = #E5EDE6
foreground = #202E18
cursor-color = #202E18
cursor-text = #202E18
selection-background = #ADE48C
selection-foreground = #202E18
