palette = 0=#0F191F
palette = 1=#DE6E7C
palette = 2=#90FF6B
palette = 3=#B77E64
palette = 4=#8190D4
palette = 5=#B279A7
palette = 6=#66A5AD
palette = 7=#C6D5CF
palette = 8=#C6D5CF
palette = 9=#92A0E2
palette = 10=#65B8C1
palette = 11=#A0FF85
palette = 12=#E8838F
palette = 13=#CF86C1
palette = 14=#263945
palette = 15=#98A39E

# Other settings
background = #0F191F
foreground = #C6D5CF
cursor-color = #CEDDD7
cursor-text = #C6D5CF
selection-background = #3A3E3D
selection-foreground = #C6D5CF
