palette = 0=#E2E2E2
palette = 1=#DC5284
palette = 2=#628562
palette = 3=#C48562
palette = 4=#0084A3
palette = 5=#896788
palette = 6=#008586
palette = 7=#555555
palette = 8=#E2E2E2
palette = 9=#006F89
palette = 10=#006F70
palette = 11=#487249
palette = 12=#BE3C6D
palette = 13=#7F4C7E
palette = 14=#BFBABB
palette = 15=#777777

# Other settings
background = #E2E2E2
foreground = #555555
cursor-color = #555555
cursor-text = #555555
selection-background = #CCCCCC
selection-foreground = #555555
