palette = 0=#F0F0CA
palette = 1=#A8334C
palette = 2=#4F6C31
palette = 3=#944927
palette = 4=#286486
palette = 5=#88507D
palette = 6=#3B8992
palette = 7=#353535
palette = 8=#353535
palette = 9=#1D5573
palette = 10=#94253E
palette = 11=#3F5A22
palette = 12=#803D1C
palette = 13=#7B3B70
palette = 14=#C6C6A3
palette = 15=#5C5C5C

# Other settings
background = #F0F0CA
foreground = #353535
cursor-color = #353535
cursor-text = #353535
selection-background = #D7D7D7
selection-foreground = #353535
