palette = 0=#F0EDEC
palette = 1=#A8334C
palette = 2=#4F6C31
palette = 3=#944927
palette = 4=#286486
palette = 5=#88507D
palette = 6=#3B8992
palette = 7=#2C363C
palette = 8=#2C363C
palette = 9=#1D5573
palette = 10=#94253E
palette = 11=#3F5A22
palette = 12=#803D1C
palette = 13=#7B3B70
palette = 14=#CFC1BA
palette = 15=#4F5E68

# Other settings
background = #F0EDEC
foreground = #2C363C
cursor-color = #2C363C
cursor-text = #2C363C
selection-background = #CBD9E3
selection-foreground = #2C363C
