palette = 0=#191919
palette = 1=#DE6E7C
palette = 2=#819B69
palette = 3=#B77E64
palette = 4=#6099C0
palette = 5=#B279A7
palette = 6=#66A5AD
palette = 7=#BBBBBB
palette = 8=#BBBBBB
palette = 9=#61ABDA
palette = 10=#E8838F
palette = 11=#8BAE68
palette = 12=#D68C67
palette = 13=#CF86C1
palette = 14=#3D3839
palette = 15=#8E8E8E

# Other settings
background = #191919
foreground = #BBBBBB
cursor-color = #C9C9C9
cursor-text = #BBBBBB
selection-background = #404040
selection-foreground = #BBBBBB
