#!/bin/bash

# uninstall.sh
# OS-agnostic script to remove dotfiles symlinks and clean up cache/state.

# 1. Determine the root dotfiles directory (moving one level up from 'scripts/')
DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Function to check if a command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Ask for confirmation unless --force flag is passed
if [[ "$1" != "--force" ]]; then
    read -p "This will remove all dotfiles symlinks and caches. Are you sure? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Aborted."
        exit 1
    fi
fi

# 2. Unstow if Stow is available
if command_exists stow; then
    echo "Unstowing packages..."
    # Array updated to match stow-install.sh
    PACKAGES=(
        "git"
        "ghostty"
        "ideavim"
        "nvim"
        "tmux"
        "zsh"
    )
    for package in "${PACKAGES[@]}"; do
        # -v: verbose
        # -D: delete (unstow)
        # -d: source directory (forces the exact source folder to prevent path errors)
        # -t: target directory
        stow -v -D -d "$DOTFILES_DIR" -t "$HOME" "$package" 2>/dev/null || true
    done
fi

# 3. Manual cleanup of potential leftovers (symlinks or directories in HOME)
echo "Cleaning up configuration leftovers..."

# Git
rm -f "$HOME/.gitconfig"
rm -f "$HOME/.gitignore_global"

# Tmux
rm -f "$HOME/.tmux.conf"

# Zsh
rm -rf "$HOME/.zsh"
rm -f "$HOME/.zshrc"

# Ghostty
rm -rf "$HOME/.config/ghostty"

# Ideavim
rm -f "$HOME/.ideavimrc"
rm -f "$HOME/.ideavimrc-doc"

# Neovim (config)
rm -rf "$HOME/.config/nvim"

# 4. Clean up cache and state generated by runtime applications
echo "Cleaning up cache and state..."

# Neovim (Uses XDG base dirs natively on both Linux and macOS)
rm -rf "$HOME/.cache/nvim"
rm -rf "$HOME/.local/share/nvim"
rm -rf "$HOME/.local/state/nvim"

# Java Language Server (JDTLS cache created by Neovim during Java development)
rm -rf "$HOME/.cache/jdtls"

# Cleanup empty .config if we made it empty (optional, but clean)
rmdir "$HOME/.config" 2>/dev/null || true

echo "Done! Dotfiles have been uninstalled and caches purged."

